services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
    - backend
  backend:
    build: ./backend
    env_file: ./backend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    env_file: .env
    ports:
      - "8000:5432"
    volumes:
      - pgproddata:/var/lib/postgresql/data
    restart: always
volumes:
    pgproddata: